export { default as apple } from "./apple.svg?raw";
export { default as appStore } from "./app-store.svg?raw";
export { default as arch } from "./arch.svg?raw";
export { default as chrome } from "./chrome.svg?raw";
export { default as edge } from "./edge.svg?raw";
export { default as firefox } from "./firefox.svg?raw";
export { default as github } from "./github.svg?raw";
export { default as googlePlay } from "./google-play.svg?raw";
export { default as windows } from "./windows.svg?raw";
