import { z } from "zod";

import { desktopAppSchema } from "./schema";

export const _desktopApps: z.input<typeof desktopAppSchema>[] = [
  {
    name: "Git",
    description: "Distributed version control system for tracking changes in source code.",
    monetization: "free",
    tags: ["development", "version control", "open source"],
    stores: [
      { source: "winget", id: "Git.Git" },
      { source: "brew", id: "git" },
      { source: "yay", id: "git" },
      { source: "mise", id: null },
    ],
  },
  {
    name: "mise",
    description: "Polyglot tool version manager that installs project runtimes such as Node, Python, and Go.",
    monetization: "free",
    tags: ["development", "version manager", "open source"],
    stores: [
      { source: "winget", id: "jdx.mise" },
      { source: "brew", id: "mise" },
      { source: "yay", id: "mise" },
      { source: "mise", id: null },
    ],
  },
  {
    name: "ONLYOFFICE",
    description: "Open source office suite for documents, spreadsheets, and presentations.",
    monetization: "freemium_plus",
    tags: ["office", "documents", "open source"],
    stores: [
      { source: "winget", id: "ONLYOFFICE.DesktopEditors" },
      { source: "brew", id: "onlyoffice", cask: true },
      { source: "yay", id: "onlyoffice-bin" },
      { source: "mise", id: null },
    ],
  },
  {
    name: "Bun",
    description: "Fast all in one JavaScript runtime, bundler, test runner, and package manager.",
    monetization: "free",
    tags: ["javascript", "runtime", "development", "open source"],
    stores: [
      { source: "winget", id: "Oven-sh.Bun" },
      { source: "brew", id: "bun" },
      { source: "yay", id: "bun-bin" },
      { source: "mise", id: "bun" },
    ],
  },
  {
    name: "NanaZip",
    description: "Modern 7-Zip derivative for Windows with extra archive formats and security features.",
    monetization: "free",
    tags: ["utilities", "archiving", "open source", "windows"],
    stores: [
      { source: "winget", id: "M2Team.NanaZip" },
      { source: "brew", id: null },
      { source: "yay", id: null },
      { source: "mise", id: null },
    ],
  },
  {
    name: "Desktop Plus",
    description: "GitHub Desktop fork with commit search, multiple accounts, a commit graph, and Linux support.",
    monetization: "free",
    tags: ["development", "git", "open source"],
    stores: [
      { source: "winget", id: "DesktopPlus.DesktopPlus" },
      { source: "brew", id: "desktop-plus/tap/desktop-plus", cask: true },
      { source: "yay", id: "desktop-plus-bin" },
      { source: "mise", id: null },
    ],
  },
  {
    name: "Microsoft Edge",
    description: "Microsoft's Chromium based browser with vertical tabs, collections, and built in features.",
    monetization: "free",
    tags: ["browser", "microsoft"],
    stores: [
      { source: "winget", id: "Microsoft.Edge" },
      { source: "brew", id: "microsoft-edge", cask: true },
      { source: "yay", id: "microsoft-edge-stable-bin" },
      { source: "mise", id: null },
    ],
  },
  {
    name: "Firefox",
    description: "Mozilla's independent, open source browser focused on privacy and customization.",
    monetization: "free",
    tags: ["browser", "open source"],
    stores: [
      { source: "winget", id: "Mozilla.Firefox" },
      { source: "brew", id: "firefox", cask: true },
      { source: "yay", id: "firefox" },
      { source: "mise", id: null },
    ],
  },
  {
    name: "Microsoft PowerToys",
    description: "Microsoft's set of Windows utilities such as FancyZones, PowerToys Run, and Peek.",
    monetization: "free",
    tags: ["utilities", "microsoft", "windows"],
    stores: [
      { source: "winget", id: "Microsoft.PowerToys" },
      { source: "brew", id: null },
      { source: "yay", id: null },
      { source: "mise", id: null },
    ],
  },
  {
    name: "Neovim",
    description: "Extensible, modal text editor that modernizes Vim with Lua scripting and built in LSP.",
    monetization: "free",
    tags: ["development", "editor", "open source"],
    stores: [
      { source: "winget", id: "Neovim.Neovim" },
      { source: "brew", id: "neovim" },
      { source: "yay", id: "neovim" },
      { source: "mise", id: "neovim" },
    ],
  },
  {
    name: "OBS Studio",
    description: "Open source app for recording and live streaming, with scenes, sources, and plugins.",
    monetization: "free",
    tags: ["video", "streaming", "open source"],
    stores: [
      { source: "winget", id: "OBSProject.OBSStudio" },
      { source: "brew", id: "obs", cask: true },
      { source: "yay", id: "obs-studio" },
      { source: "mise", id: null },
    ],
  },
  {
    name: "qBittorrent",
    description: "Open source BitTorrent client with a built in search engine and no ads.",
    monetization: "free",
    tags: ["utilities", "torrent", "open source"],
    stores: [
      { source: "winget", id: "qBittorrent.qBittorrent" },
      { source: "brew", id: "qbittorrent", cask: true },
      { source: "yay", id: "qbittorrent" },
      { source: "mise", id: null },
    ],
  },
  {
    name: "Steam",
    description: "Valve's game store and launcher for buying, managing, and playing games.",
    monetization: "freemium_plus",
    tags: ["gaming"],
    stores: [
      { source: "winget", id: "Valve.Steam" },
      { source: "brew", id: "steam", cask: true },
      { source: "yay", id: "steam" },
      { source: "mise", id: null },
    ],
  },
  {
    name: "yt-dlp",
    description: "Command line downloader for YouTube and many other sites, a fork of youtube-dl.",
    monetization: "free",
    tags: ["utilities", "video", "open source"],
    stores: [
      { source: "winget", id: "yt-dlp.yt-dlp" },
      { source: "brew", id: "yt-dlp" },
      { source: "yay", id: "yt-dlp" },
      { source: "mise", id: "yt-dlp" },
    ],
  },
  {
    name: "Visual Studio Code",
    description: "Microsoft's extensible code editor with debugging, Git, and a large extension marketplace.",
    monetization: "free",
    tags: ["development", "editor", "microsoft"],
    stores: [
      { source: "winget", id: "Microsoft.VisualStudioCode" },
      { source: "brew", id: "visual-studio-code", cask: true },
      { source: "yay", id: "visual-studio-code-bin" },
      { source: "mise", id: null },
    ],
  },
  {
    name: "Typst",
    description: "Modern typesetting system and compiler that serves as an alternative to LaTeX.",
    monetization: "free",
    tags: ["documents", "typesetting", "open source"],
    stores: [
      { source: "winget", id: "Typst.Typst" },
      { source: "brew", id: "typst" },
      { source: "yay", id: "typst" },
      { source: "mise", id: "typst" },
    ],
  },
  {
    name: "zoxide",
    description: "Smarter cd command that jumps to the directories you use most.",
    monetization: "free",
    tags: ["development", "shell", "open source"],
    stores: [
      { source: "winget", id: "ajeetdsouza.zoxide" },
      { source: "brew", id: "zoxide" },
      { source: "yay", id: "zoxide" },
      { source: "mise", id: "zoxide" },
    ],
  },
  {
    name: "bat",
    description: "Cat clone with syntax highlighting, Git integration, and line numbers.",
    monetization: "free",
    tags: ["development", "shell", "open source"],
    stores: [
      { source: "winget", id: "sharkdp.bat" },
      { source: "brew", id: "bat" },
      { source: "yay", id: "bat" },
      { source: "mise", id: "bat" },
    ],
  },
  {
    name: "ripgrep",
    description: "Fast recursive search tool that respects gitignore files and skips binaries.",
    monetization: "free",
    tags: ["development", "search", "open source"],
    stores: [
      { source: "winget", id: "BurntSushi.ripgrep.MSVC" },
      { source: "brew", id: "ripgrep" },
      { source: "yay", id: "ripgrep" },
      { source: "mise", id: "ripgrep" },
    ],
  },
  {
    name: "Atuin",
    description: "Shell history search and sync with an optional encrypted server.",
    monetization: "free",
    tags: ["development", "shell", "open source"],
    stores: [
      { source: "winget", id: "Atuinsh.Atuin" },
      { source: "brew", id: "atuin" },
      { source: "yay", id: "atuin" },
      { source: "mise", id: "atuin" },
    ],
  },
  {
    name: "chezmoi",
    description: "Manages dotfiles across machines from a single source of truth.",
    monetization: "free",
    tags: ["utilities", "dotfiles", "open source"],
    stores: [
      { source: "winget", id: "twpayne.chezmoi" },
      { source: "brew", id: "chezmoi" },
      { source: "yay", id: "chezmoi" },
      { source: "mise", id: "chezmoi" },
    ],
  },
  {
    name: "fastfetch",
    description: "Fast system information tool that prints a logo alongside hardware and OS details.",
    monetization: "free",
    tags: ["utilities", "system information", "open source"],
    stores: [
      { source: "winget", id: "Fastfetch-cli.Fastfetch" },
      { source: "brew", id: "fastfetch" },
      { source: "yay", id: "fastfetch" },
      { source: "mise", id: "fastfetch" },
    ],
  },
  {
    name: "television",
    description: "Fuzzy finder for the terminal with channels for files, history, and more.",
    monetization: "free",
    tags: ["development", "search", "tv", "open source"],
    stores: [
      { source: "winget", id: "alexpasmantier.television" },
      { source: "brew", id: "television" },
      { source: "yay", id: "television" },
      { source: "mise", id: "television" },
    ],
  },
  {
    name: "rumdl",
    description: "Fast Markdown linter and formatter written in Rust.",
    monetization: "free",
    tags: ["development", "markdown", "open source"],
    stores: [
      { source: "winget", id: "rvben.rumdl" },
      { source: "brew", id: "rumdl" },
      { source: "yay", id: "rumdl" },
      { source: "mise", id: "rumdl" },
    ],
  },
  {
    name: "uv",
    description: "Extremely fast Python package and project manager from Astral.",
    monetization: "free",
    tags: ["python", "development", "open source"],
    stores: [
      { source: "winget", id: "astral-sh.uv" },
      { source: "brew", id: "uv" },
      { source: "yay", id: "uv" },
      { source: "mise", id: "uv" },
    ],
  },
  {
    name: "Starship",
    description: "Minimal, fast, and customizable prompt for any shell.",
    monetization: "free",
    tags: ["development", "shell", "open source"],
    stores: [
      { source: "winget", id: "Starship.Starship" },
      { source: "brew", id: "starship" },
      { source: "yay", id: "starship" },
      { source: "mise", id: "starship" },
    ],
  },
  {
    name: "Zed",
    description: "High performance multiplayer code editor from the creators of Atom and Tree-sitter.",
    monetization: "free",
    tags: ["development", "editor", "open source"],
    stores: [
      { source: "winget", id: "ZedIndustries.Zed" },
      { source: "brew", id: "zed", cask: true },
      { source: "yay", id: "zed" },
      { source: "mise", id: null },
    ],
  },
];

export const desktopApps = z.array(desktopAppSchema).parse(_desktopApps);
